[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
]
ffi = true
# if we allow ffi true, if makes foundry to run command directly in our termianl
# we usually keep it false;
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
